#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Photolane.Droid.Resource", IsApplication=true)]

namespace Photolane.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ByteSmith.WindowsAzure.Messaging.Resource.String.library_name = global::Photolane.Droid.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::Photolane.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cameraIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cameraUpload = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gravatar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int addFileImageButton = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int cameraImageButton = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int captionEditText = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int captionTextView = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int loginButton = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int photoHolderImageView = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int photoTimeStampTextView = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int profilePictureImageView = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int progressBar = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int sendButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int timelineListView = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TimelineListView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
